const root = "G:/Lucas-Initiative/LucasCore";
const ps = "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe";

module.exports = {
  apps: [
    {
      name: "branch-api-20086",
      script: ps,
      args: "-NoProfile -ExecutionPolicy Bypass -File scripts/dev-api.ps1 -Port 20086",
      cwd: root,
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "20s",
      kill_timeout: 10000,
      env: {
        LCC_API_PORT: "20086",
        LCC_OS_AGENT_REGISTRY: "disabled",
        LCC_MAX_ACTIVE_SESSIONS: "20",
      },
      error_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-api-20086-error.log",
      out_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-api-20086-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "branch-web-20085",
      script: ps,
      args: "-NoProfile -ExecutionPolicy Bypass -File scripts/dev-web.ps1 -Port 20085 -ApiOrigin http://127.0.0.1:20086 -WsOrigin ws://127.0.0.1:20086 -HostName 127.0.0.1",
      cwd: root,
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "10s",
      kill_timeout: 10000,
      env: {
        VITE_LCC_API_ORIGIN: "http://127.0.0.1:20086",
        VITE_LCC_WS_ORIGIN: "ws://127.0.0.1:20086",
        LCC_API_ORIGIN: "http://127.0.0.1:20086",
        LCC_WS_ORIGIN: "ws://127.0.0.1:20086",
      },
      error_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-web-20085-error.log",
      out_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-web-20085-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "branch-ledger-20087",
      script: "tools/ceo-ledger-board-server.cjs",
      cwd: root,
      interpreter: "node",
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "10s",
      kill_timeout: 5000,
      env: {
        CEO_LEDGER_PORT: "20087",
        LCC_API_BASE: "http://127.0.0.1:20086",
      },
      error_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-ledger-20087-error.log",
      out_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-ledger-20087-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "branch-inbound-20088",
      script: ps,
      args: "-NoProfile -ExecutionPolicy Bypass -File scripts/dev-api.ps1 -Port 20088",
      cwd: root,
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "20s",
      kill_timeout: 10000,
      env: {
        LCC_API_PORT: "20088",
        LCC_INBOUND_ONLY: "1",
        LCC_OS_AGENT_REGISTRY: "disabled",
        LCC_MAX_ACTIVE_SESSIONS: "0",
      },
      error_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-inbound-20088-error.log",
      out_file: "G:/Lucas-Initiative/LucasCore/data/system-logs/pm2/branch-inbound-20088-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
