const root = "D:/Lucas Core v0.1";
const ps = "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe";

module.exports = {
  apps: [
    {
      name: "lcc-api-9001",
      script: ps,
      args: "-NoProfile -ExecutionPolicy Bypass -File scripts/dev-api.ps1 -Port 9001",
      cwd: root,
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "20s",
      kill_timeout: 10000,
      env: {
        LCC_API_PORT: "9001",
        LCC_OS_AGENT_REGISTRY: "disabled",
        LCC_MAX_ACTIVE_SESSIONS: "20",
      },
      error_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-api-9001-error.log",
      out_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-api-9001-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "lcc-web-9000",
      script: ps,
      args: "-NoProfile -ExecutionPolicy Bypass -File scripts/dev-web.ps1 -Port 9000 -ApiOrigin http://127.0.0.1:9001 -WsOrigin ws://127.0.0.1:9001 -HostName 127.0.0.1",
      cwd: root,
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "10s",
      kill_timeout: 10000,
      env: {
        VITE_LCC_API_ORIGIN: "http://127.0.0.1:9001",
        VITE_LCC_WS_ORIGIN: "ws://127.0.0.1:9001",
        LCC_API_ORIGIN: "http://127.0.0.1:9001",
        LCC_WS_ORIGIN: "ws://127.0.0.1:9001",
      },
      error_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-web-9000-error.log",
      out_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-web-9000-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "lcc-ledger-9100",
      script: "tools/ceo-ledger-board-server.cjs",
      cwd: root,
      interpreter: "node",
      watch: false,
      windowsHide: true,
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: "10s",
      kill_timeout: 5000,
      env: {
        CEO_LEDGER_PORT: "9100",
        LCC_API_BASE: "http://127.0.0.1:9001",
      },
      error_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-ledger-9100-error.log",
      out_file: "D:/Lucas Core v0.1/data/system-logs/pm2/lcc-ledger-9100-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
